#ifndef APP_BOARD_CONFIG_H
#define APP_BOARD_CONFIG_H

#include <stdint.h>

#define BOARD_PWM_PERIOD_COUNTS       4499U
#define BOARD_PWM_FULL_COUNTS         4500U
#define BOARD_BATTERY_DIVIDER_NUM     11U
#define BOARD_BATTERY_DIVIDER_DEN     1U
#define BOARD_BATTERY_CELLS           2U
#define BOARD_BATTERY_ADC_SAMPLES     16U
#define BOARD_ADC_REF_MV              3300U
#define BOARD_ADC_MAX_COUNTS          4095U
#define BOARD_BATT_LOW_MV             7000U
#define BOARD_BATT_CRITICAL_MV        6600U
#define BOARD_BATT_CRITICAL_HOLD_MS   1000U
#define BOARD_BATT_RECOVER_MV         6800U
#define BOARD_BATT_FULL_MV            8400U
#define BOARD_BATT_EMPTY_MV           6600U

#define BOARD_CONTROL_LOOP_HZ         500U
#define BOARD_MAX_ANGLE_DEG           18.0f
#define BOARD_MAX_YAW_RATE_DPS        90.0f
#define BOARD_LEVEL_GAIN_DPS_PER_DEG  2.2f
#define BOARD_MAX_LEVEL_RATE_DPS      150.0f
#define BOARD_RC_EXPO_PERCENT         30U
#define BOARD_YAW_GYRO_DIRECTION      (-1)
#define BOARD_RC_DEADBAND             20
#define BOARD_ARM_SWITCH_DEBOUNCE_MS  80U
#define BOARD_IMU_GYRO_LPF_ALPHA      0.45f
#define BOARD_IMU_ACCEL_LPF_ALPHA     0.30f
#define BOARD_ARM_THROTTLE_MAX        50U
#define BOARD_RC_TIMEOUT_MS           300U
#define BOARD_IMU_FAILSAFE_TIMEOUT_MS 250U
#define BOARD_MOTOR_IDLE_PERMILLE     80U
#define BOARD_MOTOR_IDLE_MAX_PERMILLE 200U
#define BOARD_MOTOR_MAX_PERMILLE      700U
#define BOARD_MOTOR_MAX_SPREAD_PERMILLE 360U
#define BOARD_THROTTLE_SLEW_PER_LOOP  15U
#define BOARD_MOTOR_TEST_WINDOW_MS    5000U

typedef enum {
  BOARD_MOTOR_1 = 0,
  BOARD_MOTOR_2 = 1,
  BOARD_MOTOR_3 = 2,
  BOARD_MOTOR_4 = 3
} board_motor_id_t;

#endif /* APP_BOARD_CONFIG_H */
