#ifndef APP_BOARD_CONFIG_H
#define APP_BOARD_CONFIG_H

#include <stdint.h>

#define BOARD_PWM_PERIOD_COUNTS       4499U
#define BOARD_PWM_FULL_COUNTS         4500U
#define BOARD_BATTERY_DIVIDER_NUM     11U
#define BOARD_BATTERY_DIVIDER_DEN     1U
#define BOARD_BATTERY_CELLS           2U
#define BOARD_BATTERY_ADC_SAMPLES     16U
#define BOARD_ADC_REF_MV              3300U
#define BOARD_ADC_MAX_COUNTS          4095U
#define BOARD_BATT_LOW_MV             7000U
#define BOARD_BATT_CRITICAL_MV        6600U
#define BOARD_BATT_CRITICAL_HOLD_MS   1000U
#define BOARD_BATT_RECOVER_MV         6800U
#define BOARD_BATT_FULL_MV            8400U
#define BOARD_BATT_EMPTY_MV           6600U

#define BOARD_CONTROL_LOOP_HZ         500U
#define BOARD_MAX_ANGLE_DEG           28.0f
#define BOARD_MAX_YAW_RATE_DPS        130.0f
#define BOARD_LEVEL_GAIN_DPS_PER_DEG  3.8f
#define BOARD_MAX_LEVEL_RATE_DPS      240.0f
#define BOARD_RC_EXPO_PERCENT         18U
#define BOARD_THROTTLE_EXPO_PERCENT   35U
#define BOARD_THROTTLE_HOVER_PERMILLE 500U
#define BOARD_ITERM_RELAX_RATE_DPS    45.0f
#define BOARD_ITERM_ERROR_LIMIT_DPS   90.0f
#define BOARD_ITERM_DECAY             0.995f
#define BOARD_AIRMODE_ENABLE          1U
#define BOARD_AIRMODE_START_THROTTLE  80U
#define BOARD_CRASH_DISARM_ENABLE     0U
#define BOARD_CRASH_ANGLE_DEG         80.0f
#define BOARD_CRASH_GYRO_DPS          900.0f
#define BOARD_CRASH_HOLD_MS           350U
#define BOARD_YAW_GYRO_DIRECTION      (-1)
#define BOARD_RC_DEADBAND             20
#define BOARD_ARM_SWITCH_DEBOUNCE_MS  150U
#define BOARD_IMU_GYRO_LPF_HZ         80.0f
#define BOARD_IMU_ACCEL_LPF_HZ        15.0f
#define BOARD_IMU_DCM_KP              2.5f
#define BOARD_IMU_DCM_KI              0.05f
#define BOARD_IMU_ACC_MIN_G_SQ        0.72f
#define BOARD_IMU_ACC_MAX_G_SQ        1.35f
#define BOARD_BARO_TIMEOUT_MS         250U
#define BOARD_BARO_PRESSURE_MIN_PA    30000
#define BOARD_BARO_PRESSURE_MAX_PA    110000
#define BOARD_BARO_BASELINE_SAMPLES   16U
#define BOARD_BARO_BASELINE_STEP_MAX_PA 150
#define BOARD_BARO_ALT_SPIKE_REJECT_CM 250
#define BOARD_BARO_ALT_LPF_HZ         3.0f
#define BOARD_BARO_VEL_LPF_HZ         2.0f
#define BOARD_ALT_IMU_ACC_LPF_HZ      8.0f
#define BOARD_ALT_IMU_ACC_DEADBAND_CMS2 25.0f
#define BOARD_ALT_IMU_ACC_LIMIT_CMS2  800.0f
#define BOARD_ALT_BARO_POS_BLEND      0.10f
#define BOARD_ALT_BARO_VEL_BLEND      0.12f
#define BOARD_BARO_VEL_DEADBAND_CMS   8
#define BOARD_BARO_VEL_LIMIT_CMS      600
#define BOARD_ALT_HOLD_DB_PERMILLE    60
#define BOARD_ALT_HOLD_DB_CM          8
#define BOARD_ALT_ENABLE_THROTTLE_MIN 80U
#define BOARD_ALT_BASE_MIN_PERMILLE   480U
#define BOARD_ALT_BASE_MAX_PERMILLE   680U
#define BOARD_ALT_OUTPUT_SLEW_PER_SAMPLE 12
#define BOARD_ALT_HOLD_POS_P          1.2f
#define BOARD_ALT_HOLD_MAX_VEL_CMS    160
#define BOARD_ALT_STICK_MAX_VEL_CMS   220
#define BOARD_ALT_VEL_P               0.95f
#define BOARD_ALT_VEL_I               0.26f
#define BOARD_ALT_I_LIMIT_PERMILLE    110.0f
#define BOARD_ALT_OUTPUT_LIMIT_PERMILLE 180
#define BOARD_ALT_TILT_LIMIT_DEG      45.0f
#define BOARD_ARM_THROTTLE_MAX        50U
#define BOARD_INFLIGHT_ARM_LOST_HOLD_MS 600U
#define BOARD_RC_TIMEOUT_MS           700U
#define BOARD_IMU_FAILSAFE_TIMEOUT_MS 400U
#define BOARD_MOTOR_IDLE_PERMILLE     80U
#define BOARD_MOTOR_IDLE_MAX_PERMILLE 200U
#define BOARD_MOTOR_MAX_PERMILLE      760U
#define BOARD_MOTOR_MAX_SPREAD_PERMILLE 430U
#define BOARD_THROTTLE_SLEW_PER_LOOP  15U
#define BOARD_MOTOR_TEST_WINDOW_MS    5000U

typedef enum {
  BOARD_MOTOR_1 = 0,
  BOARD_MOTOR_2 = 1,
  BOARD_MOTOR_3 = 2,
  BOARD_MOTOR_4 = 3
} board_motor_id_t;

#endif /* APP_BOARD_CONFIG_H */
